formatHeader = "\033[{}m"

class FGColors:
	black = formatHeader.format("30")
	red = formatHeader.format("31")
	green = formatHeader.format("32")
	yellow = formatHeader.format("33")
	blue = formatHeader.format("34")
	magenta = formatHeader.format("35")
	cyan = formatHeader.format("36")
	white = formatHeader.format("37")
	Bblack = formatHeader.format("30;0")
	Bred = formatHeader.format("31;0")
	Bgreen = formatHeader.format("32;0")
	Byellow = formatHeader.format("33;0")
	Bblue = formatHeader.format("34;0")
	Bmagenta = formatHeader.format("35;0")
	Bcyan = formatHeader.format("36;0")
	Bwhite = formatHeader.format("37;0")

class BGColors:
	black = formatHeader.format("40")
	red = formatHeader.format("41")
	green = formatHeader.format("42")
	yellow = formatHeader.format("44")
	blue = formatHeader.format("44")
	magenta = formatHeader.format("45")
	cyan = formatHeader.format("46")
	white = formatHeader.format("47")
	black = formatHeader.format("40;1")
	red = formatHeader.format("41;1")
	green = formatHeader.format("42;1")
	yellow = formatHeader.format("44;1")
	blue = formatHeader.format("44;1")
	magenta = formatHeader.format("45;1")
	cyan = formatHeader.format("46;1")
	white = formatHeader.format("47;1")

class Formats:
	reset = formatHeader.format("0")
	bold = formatHeader.format("1")
	dark = formatHeader.format("2")
	italic = formatHeader.format("3")
	underline = formatHeader.format("4")
	blink = formatHeader.format("5")
	normal = formatHeader.format("6")
	reverse = formatHeader.format("7")
	transparent = formatHeader.format("8")
	crossover = formatHeader.format("9")